disabled_rules:
  - trailing_newline
  - todo
  - cyclomatic_complexity

excluded:
  - DiaCare/Network
  - Carthage
  - Pods

identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - z

opt_in_rules:
  - colon
  - control_statement
  - force_cast
  - force_try
  - indentation_width
  - operator_usage_whitespace
  - unused_capture_list
  - implicitly_unwrapped_optional
  - force_unwrapping

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Неверная аннотация инициализации массива/словаря"
    severity: error
  space_in_method_name:
    name: "Space In Method Name"
    regex: "func\\s+[a-zA-Z0-9_]+\\s+\\(.*\\)\\s*\\{"
    message: "Method name should not contain spaces"
    severity: warning
  space_between_class_keywords:
    name: "Space Between Class Keywords"
    regex: "^(final|class|struct|enum)\\s{1}[a-zA-Z0-9_]\\s{1}\\{"
    message: "There should be exactly one space between class keywords"
    severity: warning

force_unwrapping:
  severity: error

reporter: "xcode"

function_body_length:
  warning: 100
  error: 200
line_length:
  warning: 100
  error: 150
  ignores_non_comment_lines: true
type_body_length:
  warning: 400
  error: 600

line_length:
  - 150